---
tap_install:
  values:
    profile: run
    ceip_policy_disclosed: true

    shared:
      ingress_domain: run.upgrade.tapsme.org
      ingress_issuer: letsencrypt-production

    supply_chain: basic

    contour:
      envoy:
        service:
          type: LoadBalancer

    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.view.upgrade.tapsme.org

    namespace_provisioner:
      controller: true
      additional_sources:
        - git:
            ref: origin/main
            subPath: namespaces/credentials
            url: https://github.com/Mpluya/tap-gitops.git
          path: _ytt_lib/creds
      overlay_secrets:
        - name: workload-git-overlay
          namespace: tap-install
          create_export: true