apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth0-authserver
  namespace: shared-services
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/part-of: auth0-authserver