---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true

    shared:
      ingress_domain: build.upgrade.tapsme.org
      image_registry:
        project_path: "cxscssa.azurecr.io/tap-build"

    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      scanning:
        image:
          policy: lax-scan-policy
        source:
          policy: lax-scan-policy
      gitops:
        ssh_secret: "git-basic-auth"
        server_address: "https://github.com"
        repository_owner: "Mpluya"
        repository_name: "tap-gitops-config"
        branch: main
    grype:
      namespace: jeremy
      targetImagePullSecret: "registries-credentials"
      metadataStore:
        url: "https://metadata-store.view.upgrade.tapsme.org"
        caSecret:
          name: store-ca-cert
          importFromNamespace: metadata-store-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: metadata-store-secrets

    namespace_provisioner:
      controller: true
      additional_sources:
      - git:
          ref: origin/main
          subPath: ns-provisioner-samples/testing-scanning-supplychain-polyglot
          url: https://github.com/vmware-tanzu/application-accelerator-samples.git
        path: _ytt_lib/testing-scanning-supplychain-setup
      - git:
          ref: origin/main
          subPath: namespaces/credentials
          url: https://github.com/Mpluya/tap-gitops.git
        path: _ytt_lib/creds
      overlay_secrets:
      - name: workload-git-overlay
        namespace: tap-install
        create_export: true

    amr:
      observer:
        auth:
          kubernetes_service_accounts:
            autoconfigure: false
            enable: false
        cloudevent_handler:
          endpoint: amr-cloudevent-handler.view.upgrade.tapsme.org
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIFKjCCBBKgAwIBAgISBLpEDhSBTTlRdcSCHPJDwABKMA0GCSqGSIb3DQEBCwUA
          MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
          EwJSMzAeFw0yNDA0MjkxODIwNTBaFw0yNDA3MjgxODIwNDlaMDkxNzA1BgNVBAMT
          LmFtci1jbG91ZGV2ZW50LWhhbmRsZXIudmlldy51cGdyYWRlLnRhcHNtZS5vcmcw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxRyOlvF8EkTwgPHVzMdqm
          mnC8doAi6Y+7lFPwzmTrcTNMqb2BYZFxKo/NLbt8IX6JQXGUHPG8dVKOHuCFu1zn
          1lO2HbCuZm6wHfS9/A67DXWY72dTXgld5Tocn7OaX6nThBClgusPow3MGXTnMF/T
          e+RriMxl0z7nGyHi+71WpQRshnyForEkxOCSQAGeF8llrS8vdNv8wPKu/HDjm5pF
          O5TF7uDyf6JZ4DSMKuxOyw400biIrju8fmnBiOsJ/c91JFbh/a7BUu/cnFn9TSkc
          vH5mLNznpmc0m1JIXQOU70kvyiDF5l4GTVti2kKsHVbSGPHNruZQ+lggdYLBGSQf
          AgMBAAGjggIxMIICLTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
          AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFGzTjJA5f0Cb05fs
          zPhqG5YwVcqUMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsG
          AQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIG
          CCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMDkGA1UdEQQyMDCCLmFt
          ci1jbG91ZGV2ZW50LWhhbmRsZXIudmlldy51cGdyYWRlLnRhcHNtZS5vcmcwEwYD
          VR0gBAwwCjAIBgZngQwBAgEwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgA/F0tP
          1yJHWJQdZRyEvg0S7ZA3fx+FauvBvyiF7PhkbgAAAY8rTX9NAAAEAwBHMEUCIQD0
          0PiRuGv4dCz62+tbOrH8I/lVuIJ8ilnTHRgEyezIlgIgEHTgXSXWm5TcWAle8eQD
          2zTTM8hw6/RHwdX5ccYv0YQAdwDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlG
          cR+1mwAAAY8rTX9SAAAEAwBIMEYCIQCLi6RxxtFOpTBEbX2Hq7GRhVwE2bhBA7vs
          O3jXsHJyYAIhAMkVHKo7Z3vObRcY7tqzSg1+RVd0jmMdgRW3rRYKGozQMA0GCSqG
          SIb3DQEBCwUAA4IBAQAw0m2z9+VT/Yw5N55ia9ndx74vvAmcxT+zFD2a+t+/HoQq
          oyxybkqsG6qURs/xpr1b36zPnMnGtQupGDlf2PM+g+XEFvz2ZG8z4FrW2HhqTJ8x
          UFTbPyVpKlpFSS2vHr+1/chuRsu/CZhtyK8Xb1+GvLudPU++HoXYws0nxAMJ/R/1
          R2kOv1I3XxS/mspSqwurk59YkAFglgmgtQHGoLK0rZcLYMU0mSJFYPSsWA93bsoP
          vVFIRlWRNjhnZJHJwSsDiDHm87ryqloIWbWs1SdOLKY+2IHnjk8GhJEhxPSiQZvw
          G+I5V2tQVIuKVzUwQPcpRrcQlng74FznUD6OSxCz
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----

    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"
