---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true

    shared:
      ingress_domain: build.upgrade.tapsme.org
      image_registry:
        project_path: "cxscssa.azurecr.io/tap-build"

    supply_chain: testing_scanning

    namespace_provisioner:
      namespace_provisioner:
        controller: true
        additional_sources:
        - git:
            ref: origin/main
            subPath: ns-provisioner-samples/testing-scanning-supplychain
            url: https://github.com/vmware-tanzu/application-accelerator-samples.git
          path: _ytt_lib/testing-scanning-supplychain-setup