---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true

    shared:
      ingress_domain: build.upgrade.tapsme.org
      image_registry:
        project_path: "cxscssa.azurecr.io/tap-build"

    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      scanning:
        image:
          policy: lax-scan-policy
        source:
          policy: lax-scan-policy
      gitops:
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "Mpluya"
        repository_name: "tap-gitops-config"
        branch: main
    grype:
      namespace: jeremy
      targetImagePullSecret: "registries-credentials"
      metadataStore:
        url: "https://metadata-store.view.upgrade.tapsme.org"
        caSecret:
          name: store-ca-cert
          importFromNamespace: metadata-store-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: metadata-store-secrets

    namespace_provisioner:
      controller: true
      additional_sources:
      - git:
          ref: origin/main
          subPath: ns-provisioner-samples/testing-scanning-supplychain-polyglot
          url: https://github.com/vmware-tanzu/application-accelerator-samples.git
        path: _ytt_lib/testing-scanning-supplychain-setup
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"
