apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth
  namespace: tap-install
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: tap-install-secrets

  target:
    name: git-basic-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .gitPassword }}"
        username: "{{ .gitUsername }}"
        url: https://github.com
  data:
    - secretKey: gitPassword
      remoteRef:
        key: dev/upgrade-run/tap/tenant-install-secrets
        property: gitPassword
    - secretKey: gitUsername
      remoteRef:
        key: dev/upgrade-run/tap/tenant-install-secrets
        property: gitUsername
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-basic-auth
  namespace: tap-install
spec:
  toNamespaces:
    - '*'