apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-install-app
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "post-install-app"
    kapp.k14s.io/disable-wait: ""
    kapp.k14s.io/change-rule.create-order-0: "upsert after upserting tanzu-sync"
    kapp.k14s.io/change-rule.delete-order-0: "delete before deleting tanzu-sync"
spec:
  serviceAccountName: tap-installer-sa
  fetch:
    - git:
        url: ssh://git@github.com/Mpluya/tap-gitops.git
        ref: origin/main
        secretRef:
          name: sync-git-ssh
        subPath: clusters/upgrade-view/cluster-config/post-install
  template:
    - ytt: {}
  deploy:
    - kapp:
        rawOptions:
          - --dangerous-allow-empty-list-of-resources=true
          - --diff-changes=true