apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    packaging.carvel.dev/downgradable: ""
  name: acs
  namespace: tap-install
spec:
  packageRef:
    refName: application-configuration-service.tanzu.vmware.com
    versionSelection:
      constraints: ">=2.1.4"
      prereleases: {}
  serviceAccountName: tap-tap-install-sa