apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: acs
  namespace: tap-install
spec:
  packageRef:
    refName: application-configuration-service.tanzu.vmware.com
    versionSelection:
      constraints: ">=2.1.4"
      prereleases: {}
  serviceAccountName: tap-installer-sa
  values:
    - secretRef:
        name: acs-values
---
apiVersion: v1
kind: Secret
metadata:
  name: acs-values
  namespace: tap-install
stringData:
  values.yaml: |
    reconciler:
      replicas: 3